server:
  port: 8090
  servlet:
    context-path: /projetoVendas
    
spring:
  application:
    name: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/projetoVendas
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456   
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: create
